# Generated by Django 2.1.7 on 2019-02-25 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogadjaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(help_text='Unesite naziv događaja', max_length=20)),
                ('opis', models.TextField()),
                ('datumVrijeme', models.DateTimeField()),
                ('fotografija', models.ImageField(upload_to='photos/dogadjaji/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='GrupaOpcija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redniBroj', models.IntegerField()),
                ('naziv', models.CharField(help_text='Unesite naziv grupe opcije', max_length=20)),
                ('jeIskljucivOdabir', models.BooleanField()),
                ('jeObavezno', models.BooleanField()),
                ('maksimalnoOdabranih', models.IntegerField()),
                ('napomena', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Konobar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(help_text='Unesite svoje ime', max_length=20)),
                ('prezime', models.CharField(help_text='Unesite svoje prezime', max_length=20)),
                ('brojSekcije', models.IntegerField()),
                ('jeSefSmjene', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menadzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(help_text='Unesite svoje ime', max_length=20)),
                ('prezime', models.CharField(help_text='Unesite svoje prezime', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeniStavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redniBroj', models.IntegerField()),
                ('naziv', models.CharField(help_text='Unesite naziv stavke', max_length=30)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=4)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('fotografija', models.ImageField(blank=True, upload_to='photos/menu/%Y/%m/%d')),
                ('nijeUPonudi', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MeniStavkaKategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redniBroj', models.IntegerField()),
                ('naziv', models.CharField(help_text='Unesite naziv', max_length=20)),
                ('meniStavkaKategorija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MeniStavkaKategorija')),
            ],
        ),
        migrations.CreateModel(
            name='MeniStavkaKategorijaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Unesite tag', max_length=32)),
                ('meniStavkaKategorijaTag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.MeniStavkaKategorija')),
            ],
        ),
        migrations.CreateModel(
            name='MeniStavkaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Unesite tag', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijemeKreiranja', models.DateTimeField(default=django.utils.timezone.now)),
                ('vrijemeProcesiranja', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(default='AWAITING_PROCESSING')),
                ('jePrihvacena', models.BooleanField(default=False)),
                ('napomena', models.TextField(blank=True, null=True)),
                ('razlogOdbijanja', models.TextField(blank=True, null=True)),
                ('dojam', models.TextField(blank=True, null=True)),
                ('stol', models.IntegerField(blank=True, null=True)),
                ('pushEndpoint', models.TextField(blank=True, null=True)),
                ('konobarKreira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='konobar_kreirao', to='base.Konobar')),
                ('konobarProcesira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='konobar_procesirao', to='base.Konobar')),
            ],
        ),
        migrations.CreateModel(
            name='NarudzbaStavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redniBroj', models.IntegerField()),
                ('cijenaBezOpcija', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kolicina', models.IntegerField()),
                ('napomena', models.TextField()),
                ('meniStavka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.MeniStavka')),
                ('narudzba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Narudzba')),
            ],
        ),
        migrations.CreateModel(
            name='NarudzbaStavkaOdabraneOpcije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(help_text='Unesite naziv', max_length=20)),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('narudzbaStavka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.NarudzbaStavka')),
            ],
        ),
        migrations.CreateModel(
            name='Opcija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redniBroj', models.IntegerField()),
                ('naziv', models.CharField(help_text='Unesite naziv opcije', max_length=20)),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imaDodatneSastojke', models.BooleanField()),
                ('grupaOpcija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.GrupaOpcija')),
            ],
        ),
        migrations.CreateModel(
            name='OpcijaSastojak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Opcija')),
            ],
        ),
        migrations.CreateModel(
            name='Poziv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brojStola', models.IntegerField()),
                ('brojSekcije', models.IntegerField()),
                ('vrijemeKreiranja', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Promocija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(help_text='Unesite naziv promocije', max_length=20)),
                ('vaziOd', models.DateTimeField()),
                ('vaziDo', models.DateTimeField()),
                ('dogadjaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Dogadjaj')),
            ],
        ),
        migrations.CreateModel(
            name='PromotivnaCijena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=4)),
                ('meniStavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.MeniStavka')),
                ('promocija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Promocija')),
            ],
        ),
        migrations.CreateModel(
            name='Sastojak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(help_text='Unesite naziv sastojka', max_length=20)),
                ('jeUNedostaku', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SastojakMeniStavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.CharField(help_text='Unesite kolicinu', max_length=20)),
                ('meniStavka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.MeniStavka')),
                ('sastojak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Sastojak')),
            ],
        ),
        migrations.CreateModel(
            name='Stol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brojStola', models.IntegerField()),
                ('brojSekcije', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='opcijasastojak',
            name='sastojak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Sastojak'),
        ),
        migrations.AddField(
            model_name='narudzbastavkaodabraneopcije',
            name='opcija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Opcija'),
        ),
        migrations.AddField(
            model_name='menistavka',
            name='meniStavkaKategorija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.MeniStavkaKategorija'),
        ),
        migrations.AddField(
            model_name='grupaopcija',
            name='meniStavka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.MeniStavka'),
        ),
    ]
