# Generated by Django 2.1.4 on 2018-12-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sastojakmenistavka',
            name='naziv',
        ),
        migrations.AlterField(
            model_name='sastojakmenistavka',
            name='kolicina',
            field=models.CharField(help_text='Unesite kolicinu', max_length=20),
        ),
    ]
