# Generated by Django 2.1.4 on 2018-12-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181220_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menistavkakategorijatag',
            name='tag',
            field=models.CharField(help_text='Unesite tag', max_length=32),
        ),
    ]
