# Generated by Django 2.1.3 on 2018-12-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181220_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sastojak',
            name='jeUNedostaku',
            field=models.BooleanField(default=False),
        ),
    ]
