# Generated by Django 2.1.3 on 2018-12-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181223_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narudzba',
            name='dojam',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narudzba',
            name='jePrihvacena',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='narudzba',
            name='konobarKreira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='konobar_kreirao', to='base.Konobar'),
        ),
        migrations.AlterField(
            model_name='narudzba',
            name='konobarProcesira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='konobar_procesirao', to='base.Konobar'),
        ),
        migrations.AlterField(
            model_name='narudzba',
            name='napomena',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narudzba',
            name='razlogOdbijanja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narudzba',
            name='stol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='narudzba',
            name='vrijemeProcesiranja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
