# Generated by Django 2.1.3 on 2018-12-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20181223_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sastojak',
            name='jeUNedostaku',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
