# Generated by Django 2.1.4 on 2019-01-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20181223_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='narudzba',
            name='status',
            field=models.TextField(default='AWAITING_PROCESSING'),
        ),
    ]
