# Generated by Django 2.1.4 on 2019-01-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_narudzba_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='narudzba',
            name='pushEndpoint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
